Limit minio version due to breaking change
IntelLabs/coach pull request #469
Opened 2020-12-14 09:11 UTC by guyjacob

They removed the `ResponseError` class
Limit version for now to avoid crashes (in CI as well)

2020-12-14 13:20 UTC, galnov requested changes
Why not use the latest version and replace ResponseError with S3Error?

2020-12-14 17:20 UTC, guyjacob commented
TBH I wasn't sure how we'd test the change, so went for the easy solution. But I realize now that's what the multinode tests are for. So I'll change it and we'll see.

2020-12-14 18:45 UTC, galnov approved these changes

2020-12-15 07:56 UTC, guyjacob commented
Well the multinode test is failing, but for an unrelated reason apparently. So merging this regardless.

2020-12-15 08:02 UTC, merged